config/routes.rb
Omrails::Application.routes.draw do
  resources :pins

  devise_for :users

    root:to => 'pages#home'
    get 'about' => 'pages#about'
    get 'log' => 'pages#log'
    get "pins"=> 'pins#new'
    get "edit"=> 'pins#edit'
  end

   

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description

  validates :description, presence: true
end 

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  def log
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = Pin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = Pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	by <%= link_to "Mattan Griffel", "http://mattangriffel.com" %>
</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             
             <%= link_to "One Month Rails", root_path, class: "brand" %>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home', root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About', about_path %>
                        </li>
                        <li>    
                            <%= link_to 'Log', log_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                        <% if user_signed_in? %>
                        <li><%= link_to "Add +", new_user_registration_path %></li>
                        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      <% else %>
                    <li><%= link_to "Login", new_user_session_path %>
                    </li>
                      <% end %>
            </ul>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
		<% content_tag(:div,msg, class: "assert alert-#{name}") %>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
	</body>
</html>

app/views/pages/about.html.erb

<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	is a project to teach
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
	in one month. This is the sample application.
</p>

app/views/pages/home.html.erb
<div class="hero-unit">

<h1>Welcome to One Month rails!</h1>
<p>
	You've found the home page for the
<%= link_to "One Month Rails", "http://onemonthrails.com"%>
application.
</p>
<p>
	<%= link_to "Sign Up Now!", new_user_session_path, class: "btn btn-primary btn-large" %>
</p>

	</div>

app/views/pages/log.html.erb
<h1>Progress Log</h1>

<h2>Rails Installation</h2>
<p>
I did two Rails installations: Windows using railsinstaller and
Linux using virtual box, host Windows
Using the Windows installation for this project.
</p>
<h2>Adding Pages</h2>
<p>
	After adding pages it appears that I had a repetition on each page of the page title and whatever was in the body  of the page.
</p>
<p>
	I dicovered that in my application.html.erb I had an extra "yield" line. After removing this the pages displayed correctly.
</p>
<h2>Bootstrap Embellishment</h2>

	<ul> 
	<li>Installed bootstrap gem after adding 'bootstrap-sass' to gemfile </li>
	<li>Made page responsive</li>
	<li>Added top bar using grid system</li>
	<li>Added login header link</li>
	<li>Added button for 'sign up' link</li>
	<li>Added 'hero-unit' to home page</li>
</ul>
<p> I seem to have broken somthing and my app is not working properly so I decided to start over from the beginning so I could retrace my steps. However when I tried to push to github, with my new app it didnt work.I fixed this with the following steps:</p>
	<ul>
		<li>from the console: git remote rename origin upstream</li>
		<li> then: git remote add origin https://github.com/enjoycompany/omrails.git </li>
		<li>git push origin master</li>
	
	<h2> Adding Devise and Simple_form</h2>

	<p> I broke my app at this point and couldn't get the server to start properly. Finally I worked out that I had a space in the gemfile after simple_form. It is now working properly after a couple of days of pulling my hair out!!
	</p>
	<p> Problem with first attempt to create new user registration. with the following error message: undefined local variable or method `new_pin_path'. Replaced `new_pin_path' with 'new_user_registration_path' and it now works! Phew! </p>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :description, as: :text, input_html: {rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary btn-success" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
 <tr>
  <td><%= pin.description %></td>
  <td><%= link_to 'Show', pin %></td>
  <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
  <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @pins %>
  </tbody>
</table>

<br />

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <p>
              <%= @pin.description %>
            </p>
            <%= link_to 'Edit', edit_pin_path(@pin) %> |
            <%= link_to 'Back', pins_path %>
        </div>
    </div>
</div>